### ISSUE TITLE
falcor + auth0

### ISSUE THREAD

**Issue by gdi2290** [auth0/blog#78]
yo, auth0 with falcor should be pretty simple. I just noticed that it was missing in the blog post. 

> Reply I made when someone asked about adding additional  info in HTTP requests https://github.com/Netflix/falcor/issues/550#issuecomment-141145381

if you need advice on it or direction I can help

cc @chenkie

**Comment by chenkie** [comment]
In our docs now https://auth0.com/docs/quickstart/backend/falcor/

**Comment by gdi2290** [comment]
awesome :+1:
